### ISSUE TITLE
Version requise de PHP ?

### ISSUE THREAD

**Issue by Leimi** [felixgirault/parkour#9]
Hello :tada: 

J'ai l'impression qu'il y a embrouille dans la version requise de PHP pour faire marcher Parkour. Mais on me la fait pas, j'ai l'oeil :mag: :eyes: .

Dans [`filter`, le flag `ARRAY_FILTER_USE_BOTH`](https://github.com/felixgirault/parkour/blob/master/lib/Traverse.php#L67) est utilisé. Ce flag est dispo à partir de PHP 5.6.

Dans le composer.json, la version mini de PHP indiquée est 5.5.

L'idée est-elle donc de supporter 5.5, ou plutôt d'osefer :question: :dancers:

**Comment by felixgirault** [comment]
C'est bien une erreur dans le composer.json, ça a été remonté ici y'a pas longtemps : https://github.com/essence/essence/commit/b87817e4e47a947d56978a8f5a37baabb4144a32#commitcomment-12687335

N'hésite pas à faire une pull request :+1: 

Pour la petite histoire, y'avait un fallback 5.5 avant, mais c'était un peu lourd à maintenir et tester, et PHP 5.5 ne fait plus partie des versions activement supportées (http://php.net/supported-versions.php), donc OSEF indeed.

**Comment by mattjmattj** [comment]
"c'était un peu lourd à maintenir et tester" ? je rêve ! 8e22c22c7ae5e8ced16d1ca4272d9d42641ae530 était juste magique j'ai envie de dire :)

**Comment by Leimi** [comment]
Grave :crystal_ball:

**Comment by felixgirault** [comment]
YOLO je vois le futur moi ! Je me souviens même plus de PHP 5.5 tellement c'est pour les kékés !

Nan mais plus sérieusement @mattjmattj j'aimais bien l'idée, j'étais parti là-dessus au début (https://github.com/felixgirault/parkour/commit/978a78c3e9fad5214c6bd0c1d1b4e9c8784c67a2) mais c'était chiant pour les tests, ils passaient pas tous suivant la plateforme et ça niquait le code coverage... J'aurai pu m'en démerder mais bon.

Et sinon @Leimi tu les met au hasard total tes emojis ou y'a un truc ?

**Comment by Leimi** [comment]
J'suis deg car on est en 5.5 au boulot du coup :skull:

**Comment by felixgirault** [comment]
Arf...
Je me tâte à refaire la modif, mais en même temps la migration 5.5 -> 5.6 devrait pas poser de problèmes majeurs, donc ça fait du support pour pas grand chose.

**Comment by Leimi** [comment]
Oui t'embête pas :D

**Comment by felixgirault** [comment]
C'est que comme tu dois être un des seuls utilisateurs de la lib c'est couillon :D

**Comment by mattjmattj** [comment]
Ah parce que tu l'utilises EN VRAI ?

**Comment by felixgirault** [comment]
Outre le fait que ce soit maintenant utilisé dans une librairie de grande qualitayy https://github.com/essence/essence

**Comment by Leimi** [comment]
ouais je l'utilise carrément :+1: :v: :video_game: :cake:
